export interface AppConfig {
    VITE_FIREBASE_API_KEY: string;
    VITE_FIREBASE_AUTH_DOMAIN: string;
    VITE_FIREBASE_PROJECT_ID: string;
    VITE_FIREBASE_STORAGE_BUCKET: string;
    VITE_FIREBASE_MESSAGING_SENDER_ID: string;
    VITE_FIREBASE_APP_ID: string;
    VITE_FIREBASE_MEASUREMENT_ID: string;
    VITE_GEMINI_API_KEY: string;
    VITE_SUPABASE_URL: string;
    VITE_SUPABASE_SERVICE_ROLE_KEY: string;
}

let config: AppConfig | null = null;

export async function loadConfig(): Promise<AppConfig> {
    if (config) return config;

    // In development, Vite inlines these. In production, we fetch them from a JSON file
    // that is generated by the server (Cloud Run) at startup.
    try {
        const response = await fetch('/config.json');
        if (response.ok) {
            const runtimeConfig = await response.json();
            config = {
                VITE_FIREBASE_API_KEY: runtimeConfig.VITE_FIREBASE_API_KEY || import.meta.env.VITE_FIREBASE_API_KEY,
                VITE_FIREBASE_AUTH_DOMAIN: runtimeConfig.VITE_FIREBASE_AUTH_DOMAIN || import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
                VITE_FIREBASE_PROJECT_ID: runtimeConfig.VITE_FIREBASE_PROJECT_ID || import.meta.env.VITE_FIREBASE_PROJECT_ID,
                VITE_FIREBASE_STORAGE_BUCKET: runtimeConfig.VITE_FIREBASE_STORAGE_BUCKET || import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
                VITE_FIREBASE_MESSAGING_SENDER_ID: runtimeConfig.VITE_FIREBASE_MESSAGING_SENDER_ID || import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
                VITE_FIREBASE_APP_ID: runtimeConfig.VITE_FIREBASE_APP_ID || import.meta.env.VITE_FIREBASE_APP_ID,
                VITE_FIREBASE_MEASUREMENT_ID: runtimeConfig.VITE_FIREBASE_MEASUREMENT_ID || import.meta.env.VITE_FIREBASE_MEASUREMENT_ID,
                VITE_GEMINI_API_KEY: runtimeConfig.VITE_GEMINI_API_KEY || import.meta.env.VITE_GEMINI_API_KEY,
                VITE_SUPABASE_URL: runtimeConfig.VITE_SUPABASE_URL || import.meta.env.VITE_SUPABASE_URL,
                VITE_SUPABASE_SERVICE_ROLE_KEY: runtimeConfig.VITE_SUPABASE_SERVICE_ROLE_KEY || import.meta.env.VITE_SUPABASE_SERVICE_ROLE_KEY,
            };
            console.log("Runtime configuration loaded");
        }
    } catch (e) {
        console.warn("Could not load runtime config, falling back to build-time env vars", e);
    }

    if (!config) {
        config = {
            VITE_FIREBASE_API_KEY: import.meta.env.VITE_FIREBASE_API_KEY,
            VITE_FIREBASE_AUTH_DOMAIN: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
            VITE_FIREBASE_PROJECT_ID: import.meta.env.VITE_FIREBASE_PROJECT_ID,
            VITE_FIREBASE_STORAGE_BUCKET: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
            VITE_FIREBASE_MESSAGING_SENDER_ID: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
            VITE_FIREBASE_APP_ID: import.meta.env.VITE_FIREBASE_APP_ID,
            VITE_FIREBASE_MEASUREMENT_ID: import.meta.env.VITE_FIREBASE_MEASUREMENT_ID,
            VITE_GEMINI_API_KEY: import.meta.env.VITE_GEMINI_API_KEY,
            VITE_SUPABASE_URL: import.meta.env.VITE_SUPABASE_URL,
            VITE_SUPABASE_SERVICE_ROLE_KEY: import.meta.env.VITE_SUPABASE_SERVICE_ROLE_KEY,
        };
    }

    return config;
}

export function getConfig(): AppConfig {
    if (!config) {
        throw new Error("Configuration not loaded. Call loadConfig() first.");
    }
    return config;
}
