export interface AppConfig {
    VITE_FIREBASE_API_KEY: string;
    VITE_FIREBASE_AUTH_DOMAIN: string;
    VITE_FIREBASE_PROJECT_ID: string;
    VITE_FIREBASE_STORAGE_BUCKET: string;
    VITE_FIREBASE_MESSAGING_SENDER_ID: string;
    VITE_FIREBASE_APP_ID: string;
    VITE_FIREBASE_MEASUREMENT_ID: string;
    VITE_GEMINI_API_KEY: string;
    VITE_SUPABASE_URL: string;
    VITE_SUPABASE_SERVICE_ROLE_KEY: string;
    VITE_APP_PASSWORD: string;
}

let config: AppConfig | null = null;

export async function loadConfig(): Promise<AppConfig> {
    if (config) return config;

    // In development, Vite inlines these. In production, we fetch them from a JSON file
    // that is generated by the server (Cloud Run) at startup.
    try {
        const response = await fetch('/config.json');
        if (response.ok) {
            const runtimeConfig = await response.json();
            config = {
                VITE_FIREBASE_API_KEY: runtimeConfig.VITE_FIREBASE_API_KEY || import.meta.env.VITE_FIREBASE_API_KEY,
                VITE_FIREBASE_AUTH_DOMAIN: runtimeConfig.VITE_FIREBASE_AUTH_DOMAIN || import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
                VITE_FIREBASE_PROJECT_ID: runtimeConfig.VITE_FIREBASE_PROJECT_ID || import.meta.env.VITE_FIREBASE_PROJECT_ID,
                VITE_FIREBASE_STORAGE_BUCKET: runtimeConfig.VITE_FIREBASE_STORAGE_BUCKET || import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
                VITE_FIREBASE_MESSAGING_SENDER_ID: runtimeConfig.VITE_FIREBASE_MESSAGING_SENDER_ID || import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
                VITE_FIREBASE_APP_ID: runtimeConfig.VITE_FIREBASE_APP_ID || import.meta.env.VITE_FIREBASE_APP_ID,
                VITE_FIREBASE_MEASUREMENT_ID: runtimeConfig.VITE_FIREBASE_MEASUREMENT_ID || import.meta.env.VITE_FIREBASE_MEASUREMENT_ID,
                VITE_GEMINI_API_KEY: runtimeConfig.VITE_GEMINI_API_KEY || import.meta.env.VITE_GEMINI_API_KEY,
                VITE_SUPABASE_URL: runtimeConfig.VITE_SUPABASE_URL || import.meta.env.VITE_SUPABASE_URL,
                VITE_SUPABASE_SERVICE_ROLE_KEY: runtimeConfig.VITE_SUPABASE_SERVICE_ROLE_KEY || import.meta.env.VITE_SUPABASE_SERVICE_ROLE_KEY,
                VITE_APP_PASSWORD: runtimeConfig.VITE_APP_PASSWORD || import.meta.env.VITE_APP_PASSWORD || 'jobird2026',
            };
            console.log("Runtime configuration loaded");
        }
    } catch (e) {
        console.warn("Could not load runtime config, falling back to build-time env vars", e);
    }

    if (!config) {
        const env = (import.meta as any).env || {};
        const procEnv = (typeof process !== 'undefined' ? process.env : {}) as any;

        config = {
            VITE_FIREBASE_API_KEY: env.VITE_FIREBASE_API_KEY || procEnv.VITE_FIREBASE_API_KEY || '',
            VITE_FIREBASE_AUTH_DOMAIN: env.VITE_FIREBASE_AUTH_DOMAIN || procEnv.VITE_FIREBASE_AUTH_DOMAIN || '',
            VITE_FIREBASE_PROJECT_ID: env.VITE_FIREBASE_PROJECT_ID || procEnv.VITE_FIREBASE_PROJECT_ID || '',
            VITE_FIREBASE_STORAGE_BUCKET: env.VITE_FIREBASE_STORAGE_BUCKET || procEnv.VITE_FIREBASE_STORAGE_BUCKET || '',
            VITE_FIREBASE_MESSAGING_SENDER_ID: env.VITE_FIREBASE_MESSAGING_SENDER_ID || procEnv.VITE_FIREBASE_MESSAGING_SENDER_ID || '',
            VITE_FIREBASE_APP_ID: env.VITE_FIREBASE_APP_ID || procEnv.VITE_FIREBASE_APP_ID || '',
            VITE_FIREBASE_MEASUREMENT_ID: env.VITE_FIREBASE_MEASUREMENT_ID || procEnv.VITE_FIREBASE_MEASUREMENT_ID || '',
            VITE_GEMINI_API_KEY: env.VITE_GEMINI_API_KEY || procEnv.VITE_GEMINI_API_KEY || '',
            VITE_SUPABASE_URL: env.VITE_SUPABASE_URL || procEnv.VITE_SUPABASE_URL || '',
            VITE_SUPABASE_SERVICE_ROLE_KEY: env.VITE_SUPABASE_SERVICE_ROLE_KEY || procEnv.VITE_SUPABASE_SERVICE_ROLE_KEY || '',
            VITE_APP_PASSWORD: env.VITE_APP_PASSWORD || procEnv.VITE_APP_PASSWORD || 'jobird2026',
        };
    }

    return config;
}

export function getConfig(): AppConfig {
    if (!config) {
        throw new Error("Configuration not loaded. Call loadConfig() first.");
    }
    return config;
}
